name: Saguaro
author: ${project.author}
version: ${project.version}
main: com.winterhaven_mc.saguaro.PluginMain
api-version: 1.13

commands:
   saguaro:
      description: show Saguaro plugin info
      usage: /saguaro [reload]
      permission: saguaro.status
      permission-message: You do not have required saguaro.admin permission.

permissions:
    saguaro.reload:
        description: Reload Saguaro plugin config file
        default: op

    saguaro.status:
        description: View Saguaro plugin settings
        default: op

    saguaro.admin:
        description: Saguaro plugin admin commands
        default: op
        children:
            saguaro.status: true
            saguaro.reload: true